"""认证与 RBAC 模块。"""

from main_server.core.auth.auth_schema import (
    CurrentUser,
    LoginRequest,
    TokenPayload,
    TokenResponse,
)
from main_server.core.auth.auth_service import (
    authenticate,
    hash_password,
    login,
    verify_password,
)
from main_server.core.auth.jwt_auth import (
    create_access_token,
    decode_access_token,
    get_current_user,
    get_current_user_from_token,
)
from main_server.core.auth.permission import (
    DEFAULT_ROLE_SEEDS,
    Role,
    load_user_with_roles,
    normalize_roles,
    require_admin,
    require_business_user,
    require_crm_read,
    require_roles,
    role_codes,
    user_has_any_role,
    user_has_business_role,
    user_is_admin,
    user_is_admin_by_id,
)
from main_server.core.auth.user_schema import (
    ChangePasswordRequest,
    CreateUserRequest,
    ResetPasswordRequest,
    RoleInfo,
    UpdateUserRequest,
    UpdateUserRolesRequest,
    UserListResponse,
    UserResponse,
)
from main_server.core.auth.user_service import (
    change_password,
    create_user,
    delete_user,
    list_users,
    reset_password,
    update_user,
    update_user_roles,
    user_to_dict,
)

__all__ = [
    "ChangePasswordRequest",
    "CreateUserRequest",
    "CurrentUser",
    "DEFAULT_ROLE_SEEDS",
    "LoginRequest",
    "ResetPasswordRequest",
    "Role",
    "RoleInfo",
    "TokenPayload",
    "TokenResponse",
    "UpdateUserRequest",
    "UpdateUserRolesRequest",
    "UserListResponse",
    "UserResponse",
    "authenticate",
    "change_password",
    "create_access_token",
    "create_user",
    "decode_access_token",
    "delete_user",
    "get_current_user",
    "get_current_user_from_token",
    "hash_password",
    "list_users",
    "load_user_with_roles",
    "login",
    "normalize_roles",
    "require_admin",
    "require_business_user",
    "require_crm_read",
    "require_roles",
    "reset_password",
    "role_codes",
    "update_user",
    "update_user_roles",
    "user_has_any_role",
    "user_has_business_role",
    "user_is_admin",
    "user_is_admin_by_id",
    "user_to_dict",
    "verify_password",
]
